### ISSUE TITLE
payload['data'] error

### ISSUE THREAD

**Issue by seanshahkarami** [UrbanCCD-UChicago/aot-client-py#3]
I got this error when trying out the AotClient:

```python
>>> from aot_client import AotClient
>>> client = AotClient()
>>> list(client.list_projects())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/aot_client/responses.py", line 97, in __iter__
    refreshed = self._client._send_request(self.next_link)
  File "/usr/local/lib/python3.7/site-packages/aot_client/client.py", line 137, in _send_request
    return PagedResponse(payload=response.json(), client=self)
  File "/usr/local/lib/python3.7/site-packages/aot_client/responses.py", line 84, in __init__
    self._data = payload['data']
```

I installed and ran this using the `python:3.7` Docker image.

**Comment by vforgione** [comment]
Closed with  ad3b23a
